head	1.1;
access;
symbols;
locks; strict;
comment	@# @;


1.1
date	2004.08.17.08.34.45;	author lsundar;	state Exp;
branches;
next	;


desc
@@


1.1
log
@Java Source files mainly generated from JavaCC, JavaCC files to be added later
@
text
@/* Generated By:JavaCC: Do not edit this line. KuralConstants.java */
public interface KuralConstants {

  int EOF = 0;
  int KURIL = 2;
  int NEDIL = 3;
  int OTRU = 4;
  int SPACE = 5;
  int NEWLINE = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"0\"",
    "\"1\"",
    "\"2\"",
    "\" \"",
    "<NEWLINE>",
  };

}
@
