head	1.1;
access;
symbols;
locks; strict;
comment	@# @;


1.1
date	2004.08.17.08.34.45;	author lsundar;	state Exp;
branches;
next	;


desc
@@


1.1
log
@Java Source files mainly generated from JavaCC, JavaCC files to be added later
@
text
@/* Generated By:JavaCC: Do not edit this line. Tscii2TernaryConstants.java */
public interface Tscii2TernaryConstants {

  int EOF = 0;
  int OTRU = 125;
  int UYIRKURIL = 126;
  int AGARAM = 127;
  int UGARAM = 128;
  int UYIRNEDIL = 129;
  int OTRAINEDIL = 130;
  int SPACE = 131;
  int NEWLINE = 132;
  int KUTRIYALUGARA_EZHUTU = 133;
  int VALLINA_OTRU = 134;
  int MELLINA_OTRU = 135;
  int VAGARAM_OZHINDHA_IDAYINAM = 136;
  int AIDHAM = 137;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\u0001\"",
    "\"\\u0002\"",
    "\"\\u0003\"",
    "\"\\u0004\"",
    "\"\\u0005\"",
    "\"\\u0006\"",
    "\"\\u0007\"",
    "\"\\b\"",
    "\"\\u000b\"",
    "\"\\u000e\"",
    "\"\\u000f\"",
    "\"\\u0010\"",
    "\"\\u0011\"",
    "\"\\u0012\"",
    "\"\\u0013\"",
    "\"\\u0014\"",
    "\"\\u0015\"",
    "\"\\u0016\"",
    "\"\\u0017\"",
    "\"\\u0018\"",
    "\"\\u0019\"",
    "\"\\u001a\"",
    "\"\\u001b\"",
    "\"\\u001c\"",
    "\"\\u001d\"",
    "\"\\u001e\"",
    "\"\\u001f\"",
    "\"#\"",
    "\"$\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\"0\"",
    "\"1\"",
    "\"2\"",
    "\"3\"",
    "\"4\"",
    "\"5\"",
    "\"6\"",
    "\"7\"",
    "\"8\"",
    "\"9\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"?\"",
    "\"@@\"",
    "\"A\"",
    "\"B\"",
    "\"C\"",
    "\"D\"",
    "\"E\"",
    "\"F\"",
    "\"G\"",
    "\"H\"",
    "\"I\"",
    "\"J\"",
    "\"K\"",
    "\"L\"",
    "\"M\"",
    "\"N\"",
    "\"O\"",
    "\"P\"",
    "\"Q\"",
    "\"R\"",
    "\"S\"",
    "\"T\"",
    "\"U\"",
    "\"V\"",
    "\"W\"",
    "\"X\"",
    "\"Y\"",
    "\"Z\"",
    "\"[\"",
    "\"]\"",
    "\"^\"",
    "\"_\"",
    "\"`\"",
    "\"a\"",
    "\"b\"",
    "\"c\"",
    "\"d\"",
    "\"e\"",
    "\"f\"",
    "\"g\"",
    "\"h\"",
    "\"i\"",
    "\"j\"",
    "\"k\"",
    "\"l\"",
    "\"m\"",
    "\"n\"",
    "\"o\"",
    "\"p\"",
    "\"q\"",
    "\"r\"",
    "\"s\"",
    "\"t\"",
    "\"u\"",
    "\"v\"",
    "\"w\"",
    "\"x\"",
    "\"y\"",
    "\"z\"",
    "\"{\"",
    "\"|\"",
    "\"}\"",
    "\"~\"",
    "\"\\u007f\"",
    "\"\\u00a9\"",
    "\"!\"",
    "\"\\\"\"",
    "<OTRU>",
    "<UYIRKURIL>",
    "<AGARAM>",
    "<UGARAM>",
    "<UYIRNEDIL>",
    "<OTRAINEDIL>",
    "\" \"",
    "<NEWLINE>",
    "<KUTRIYALUGARA_EZHUTU>",
    "<VALLINA_OTRU>",
    "<MELLINA_OTRU>",
    "<VAGARAM_OZHINDHA_IDAYINAM>",
    "\"\\u00b7\"",
    "\"\\u00ca\"",
    "\"\\u00a1\"",
    "\"\\u00a2\"",
    "\"\\u00a6\"",
    "\"\\u00a3\"",
    "\"\\u00a7\"",
    "\"\\u00a8\"",
    "\"\\u00aa\"",
  };

}
@
