head	1.1;
access;
symbols;
locks; strict;
comment	@# @;


1.1
date	2004.08.17.08.34.45;	author lsundar;	state Exp;
branches;
next	;


desc
@@


1.1
log
@Java Source files mainly generated from JavaCC, JavaCC files to be added later
@
text
@/* Generated By:JavaCC: Do not edit this line. TsciiParserTokenManager.java */

public class TsciiParserTokenManager implements TsciiParserConstants
{
  public static  java.io.PrintStream debugStream = System.out;
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         return jjStopAtPos(0, 143);
      case 63:
         return jjStopAtPos(0, 59);
      case 160:
         return jjStopAtPos(0, 124);
      case 161:
         return jjStopAtPos(0, 147);
      case 162:
         return jjStopAtPos(0, 145);
      case 163:
         return jjStopAtPos(0, 149);
      case 166:
         return jjStopAtPos(0, 146);
      case 167:
         return jjStopAtPos(0, 150);
      case 168:
         return jjStopAtPos(0, 151);
      case 169:
         return jjStopAtPos(0, 125);
      case 170:
         return jjStopAtPos(0, 152);
      case 183:
         return jjStopAtPos(0, 126);
      case 197:
         return jjStopAtPos(0, 135);
      case 202:
         return jjStopAtPos(0, 144);
      case 203:
         return jjStopAtPos(0, 148);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
static private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
static private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x0L, 0x1015500000000000L
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x0L, 0x202aa00000000000L
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0x0L, 0xfc0000000000000L
};
static final long[] jjbitVec3 = {
   0x0L, 0x0L, 0x12a80000000000L, 0x0L
};
static final long[] jjbitVec4 = {
   0x0L, 0x0L, 0x6d500000000000L, 0x0L
};
static final long[] jjbitVec5 = {
   0x0L, 0x0L, 0x5500000000000000L, 0x101L
};
static final long[] jjbitVec6 = {
   0x0L, 0x0L, 0xaa00000000000000L, 0x202L
};
static final long[] jjbitVec7 = {
   0x0L, 0x0L, 0x0L, 0xdcL
};
static final long[] jjbitVec8 = {
   0x0L, 0x0L, 0x0L, 0x4057000L
};
static final long[] jjbitVec9 = {
   0x0L, 0x0L, 0x0L, 0x80a8000L
};
static final long[] jjbitVec10 = {
   0x0L, 0x0L, 0x0L, 0x3f00000L
};
static final long[] jjbitVec11 = {
   0x0L, 0x0L, 0x0L, 0x40570000000L
};
static final long[] jjbitVec12 = {
   0x0L, 0x0L, 0x0L, 0x80a80000000L
};
static final long[] jjbitVec13 = {
   0x0L, 0x0L, 0x0L, 0x3f000000000L
};
static private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 17;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2400L & l) != 0L)
                  {
                     if (kind > 142)
                        kind = 142;
                  }
                  else if (curChar == 63)
                  {
                     if (kind > 140)
                        kind = 140;
                  }
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 63)
                  {
                     if (kind > 137)
                        kind = 137;
                  }
                  break;
               case 9:
                  if (curChar == 63 && kind > 137)
                     kind = 137;
                  break;
               case 12:
                  if (curChar == 63 && kind > 140)
                     kind = 140;
                  break;
               case 14:
                  if ((0x2400L & l) != 0L && kind > 142)
                     kind = 142;
                  break;
               case 15:
                  if (curChar == 10 && kind > 142)
                     kind = 142;
                  break;
               case 16:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((jjbitVec0[i2] & l2) != 0L)
                  {
                     if (kind > 127)
                        kind = 127;
                  }
                  if ((jjbitVec1[i2] & l2) != 0L)
                  {
                     if (kind > 128)
                        kind = 128;
                  }
                  if ((jjbitVec2[i2] & l2) != 0L)
                  {
                     if (kind > 129)
                        kind = 129;
                  }
                  if ((jjbitVec3[i2] & l2) != 0L)
                  {
                     if (kind > 130)
                        kind = 130;
                  }
                  if ((jjbitVec4[i2] & l2) != 0L)
                  {
                     if (kind > 131)
                        kind = 131;
                  }
                  if ((jjbitVec5[i2] & l2) != 0L)
                  {
                     if (kind > 132)
                        kind = 132;
                  }
                  if ((jjbitVec6[i2] & l2) != 0L)
                  {
                     if (kind > 133)
                        kind = 133;
                  }
                  if ((jjbitVec7[i2] & l2) != 0L)
                  {
                     if (kind > 134)
                        kind = 134;
                  }
                  if ((jjbitVec8[i2] & l2) != 0L)
                  {
                     if (kind > 136)
                        kind = 136;
                  }
                  if ((jjbitVec9[i2] & l2) != 0L)
                  {
                     if (kind > 137)
                        kind = 137;
                  }
                  if ((jjbitVec10[i2] & l2) != 0L)
                  {
                     if (kind > 138)
                        kind = 138;
                  }
                  if ((jjbitVec11[i2] & l2) != 0L)
                  {
                     if (kind > 139)
                        kind = 139;
                  }
                  if ((jjbitVec12[i2] & l2) != 0L)
                  {
                     if (kind > 140)
                        kind = 140;
                  }
                  if ((jjbitVec13[i2] & l2) != 0L)
                  {
                     if (kind > 141)
                        kind = 141;
                  }
                  break;
               case 1:
                  if ((jjbitVec1[i2] & l2) != 0L && kind > 128)
                     kind = 128;
                  break;
               case 2:
                  if ((jjbitVec2[i2] & l2) != 0L && kind > 129)
                     kind = 129;
                  break;
               case 3:
                  if ((jjbitVec3[i2] & l2) != 0L && kind > 130)
                     kind = 130;
                  break;
               case 4:
                  if ((jjbitVec4[i2] & l2) != 0L && kind > 131)
                     kind = 131;
                  break;
               case 5:
                  if ((jjbitVec5[i2] & l2) != 0L && kind > 132)
                     kind = 132;
                  break;
               case 6:
                  if ((jjbitVec6[i2] & l2) != 0L && kind > 133)
                     kind = 133;
                  break;
               case 7:
                  if ((jjbitVec7[i2] & l2) != 0L && kind > 134)
                     kind = 134;
                  break;
               case 8:
                  if ((jjbitVec8[i2] & l2) != 0L && kind > 136)
                     kind = 136;
                  break;
               case 9:
                  if ((jjbitVec9[i2] & l2) != 0L && kind > 137)
                     kind = 137;
                  break;
               case 10:
                  if ((jjbitVec10[i2] & l2) != 0L && kind > 138)
                     kind = 138;
                  break;
               case 11:
                  if ((jjbitVec11[i2] & l2) != 0L && kind > 139)
                     kind = 139;
                  break;
               case 12:
                  if ((jjbitVec12[i2] & l2) != 0L && kind > 140)
                     kind = 140;
                  break;
               case 13:
                  if ((jjbitVec13[i2] & l2) != 0L && kind > 141)
                     kind = 141;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 17 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\267", null, null, null, null, null, null, null, null, "\305", null, null, 
null, null, null, null, null, "\40", "\312", "\242", "\246", "\241", "\313", "\243", 
"\247", "\250", "\252", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x1L, 0xc000000000000000L, 0x1ffffffL, 
};
static final long[] jjtoSkip = {
   0xfffffffffffffffeL, 0x3fffffffffffffffL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[17];
static private final int[] jjstateSet = new int[34];
static protected char curChar;
public TsciiParserTokenManager(SimpleCharStream stream)
{
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}
public TsciiParserTokenManager(SimpleCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 17; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

public static Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while ((curChar < 64 && (0x7ffffffeffffd9feL & (1L << curChar)) != 0L) || 
             (curChar >> 6) == 1 && (0xffffffffffffffffL & (1L << (curChar & 077))) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
@
